<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

Import all necessary modules.


In [ ]:
import numpy as np
from scipy.special import huber
import matplotlib.pyplot as plt

Compute the function for ``delta=1`` at ``r=2``


In [ ]:
huber(1., 2.)

1.5

Compute the function for different `delta` by providing a NumPy array or
list for `delta`.


In [ ]:
huber([1., 3., 5.], 4.)

array([3.5, 7.5, 8. ])

Compute the function at different points by providing a NumPy array or
list for `r`.


In [ ]:
huber(2., np.array([1., 1.5, 3.]))

array([0.5  , 1.125, 4.   ])

The function can be calculated for different `delta` and `r` by
providing arrays for both with compatible shapes for broadcasting.


In [ ]:
r = np.array([1., 2.5, 8., 10.])
deltas = np.array([[1.], [5.], [9.]])
print(r.shape, deltas.shape)

(4,) (3, 1)

In [ ]:
huber(deltas, r)

array([[ 0.5  ,  2.   ,  7.5  ,  9.5  ],
       [ 0.5  ,  3.125, 27.5  , 37.5  ],
       [ 0.5  ,  3.125, 32.   , 49.5  ]])

Plot the function for different `delta`.


In [ ]:
x = np.linspace(-4, 4, 500)
deltas = [1, 2, 3]
linestyles = ["dashed", "dotted", "dashdot"]
fig, ax = plt.subplots()
combined_plot_parameters = list(zip(deltas, linestyles))
for delta, style in combined_plot_parameters:
    ax.plot(x, huber(delta, x), label=fr"$\delta={delta}$", ls=style)
ax.legend(loc="upper center")
ax.set_xlabel("$x$")
ax.set_title(r"Huber loss function $h_{\delta}(x)$")
ax.set_xlim(-4, 4)
ax.set_ylim(0, 8)
plt.show()