<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
freqs = np.fft.fftfreq(10, 0.1)
freqs

array([ 0.,  1.,  2., ..., -3., -2., -1.])

In [ ]:
np.fft.fftshift(freqs)

array([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

Shift the zero-frequency component only along the second axis:


In [ ]:
freqs = np.fft.fftfreq(9, d=1./9).reshape(3, 3)
freqs

array([[ 0.,  1.,  2.],
       [ 3.,  4., -4.],
       [-3., -2., -1.]])

In [ ]:
np.fft.fftshift(freqs, axes=(1,))

array([[ 2.,  0.,  1.],
       [-4.,  3.,  4.],
       [-1., -3., -2.]])