<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
a = np.array([[ 0.    ,  0.2146,  0.5962,  0.    ],
              [ 0.    ,  0.7778,  0.    ,  0.    ],
              [ 0.    ,  0.    ,  0.    ,  0.    ],
              [ 0.    ,  0.    ,  0.7181,  0.2787],
              [ 0.    ,  0.    ,  0.6573,  0.3094]])
from scipy import ndimage
ndimage.histogram(a, 0, 1, 10)

array([13,  0,  2,  1,  0,  1,  1,  2,  0,  0])

With labels and no indices, non-zero elements are counted:


In [ ]:
lbl, nlbl = ndimage.label(a)
ndimage.histogram(a, 0, 1, 10, lbl)

array([0, 0, 2, 1, 0, 1, 1, 2, 0, 0])

Indices can be used to count only certain objects:


In [ ]:
ndimage.histogram(a, 0, 1, 10, lbl, 2)

array([0, 0, 1, 1, 0, 0, 1, 1, 0, 0])