<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
from scipy.stats import matrix_normal

In [ ]:
M = np.arange(6).reshape(3,2); M

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
U = np.diag([1,2,3]); U

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [ ]:
V = 0.3*np.identity(2); V

array([[ 0.3,  0. ],
       [ 0. ,  0.3]])

In [ ]:
X = M + 0.1; X

array([[ 0.1,  1.1],
       [ 2.1,  3.1],
       [ 4.1,  5.1]])

In [ ]:
matrix_normal.pdf(X, mean=M, rowcov=U, colcov=V)

0.023410202050005054

In [ ]:
# Equivalent multivariate normal
from scipy.stats import multivariate_normal
vectorised_X = X.T.flatten()
equiv_mean = M.T.flatten()
equiv_cov = np.kron(V,U)
multivariate_normal.pdf(vectorised_X, mean=equiv_mean, cov=equiv_cov)

0.023410202050005054

Alternatively, the object may be called (as a function) to fix the mean
and covariance parameters, returning a "frozen" matrix normal
random variable:


In [ ]:
rv = matrix_normal(mean=None, rowcov=1, colcov=1)
# Frozen object with the same methods but holding the given
# mean and covariance fixed.