<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
import scipy.special as sc

It is one when `x` is zero:


In [ ]:
sc.hyp1f1(0.5, 0.5, 0)

1.0

It is singular when `b` is a nonpositive integer.


In [ ]:
sc.hyp1f1(0.5, -1, 0)

inf

It is a polynomial when `a` is a nonpositive integer.


In [ ]:
a, b, x = -1, 0.5, np.array([1.0, 2.0, 3.0, 4.0])
sc.hyp1f1(a, b, x)

array([-1., -3., -5., -7.])

In [ ]:
1 + (a / b) * x

array([-1., -3., -5., -7.])

It reduces to the exponential function when `a = b`.


In [ ]:
sc.hyp1f1(2, 2, [1, 2, 3, 4])

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [ ]:
np.exp([1, 2, 3, 4])

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])