<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
import numpy as np
import scipy.special as sc

It is one when `z` is zero.


In [ ]:
sc.hyp0f1(1, 0)

1.0

It is the limit of the confluent hypergeometric function as `q`
goes to infinity.


In [ ]:
q = np.array([1, 10, 100, 1000])
v = 1
z = 1
sc.hyp1f1(q, v, z / q)

array([2.71828183, 2.31481985, 2.28303778, 2.27992985])

In [ ]:
sc.hyp0f1(v, z)

2.2795853023360673

It is related to Bessel functions.


In [ ]:
n = 1
x = np.linspace(0, 1, 5)
sc.jv(n, x)

array([0.        , 0.12402598, 0.24226846, 0.3492436 , 0.44005059])

In [ ]:
(0.5 * x)**n / sc.factorial(n) * sc.hyp0f1(n + 1, -0.25 * x**2)

array([0.        , 0.12402598, 0.24226846, 0.3492436 , 0.44005059])