<div class='alert alert-warning'>

SciPy's interactive examples with Jupyterlite are experimental and may not always work as expected. Execution of cells containing imports may result in large downloads (up to 60MB of content for the first import from SciPy). Load times when importing from SciPy may take roughly 10-20 seconds. If you notice any problems, feel free to open an [issue](https://github.com/scipy/scipy/issues/new/choose).

</div>

In [ ]:
from scipy.spatial.transform import Rotation as R
import numpy as np

Represent a single rotation:


In [ ]:
r = R.from_rotvec([0, 0, np.pi/2])
r.as_matrix()

array([[ 2.22044605e-16, -1.00000000e+00,  0.00000000e+00],
       [ 1.00000000e+00,  2.22044605e-16,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [ ]:
r.as_matrix().shape

(3, 3)

Represent a stack with a single rotation:


In [ ]:
r = R.from_quat([[1, 1, 0, 0]])
r.as_matrix()

array([[[ 0.,  1.,  0.],
        [ 1.,  0.,  0.],
        [ 0.,  0., -1.]]])

In [ ]:
r.as_matrix().shape

(1, 3, 3)

Represent multiple rotations:


In [ ]:
r = R.from_rotvec([[np.pi/2, 0, 0], [0, 0, np.pi/2]])
r.as_matrix()

array([[[ 1.00000000e+00,  0.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  2.22044605e-16, -1.00000000e+00],
        [ 0.00000000e+00,  1.00000000e+00,  2.22044605e-16]],
       [[ 2.22044605e-16, -1.00000000e+00,  0.00000000e+00],
        [ 1.00000000e+00,  2.22044605e-16,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]]])

In [ ]:
r.as_matrix().shape

(2, 3, 3)